site_name: GridCal 中文维基

pages:
  - 欢迎: 'index.md'
  - 主页: 
    - '了解 Gridcal' : 'mainpage/about.md'
    - '编者注' : 'mainpage/addition.md'
  - 安装与开发:
    - '安装' : 'start/install.md'
    - '二次开发' : 'start/develope.md'
  - 开发指南:
    - '代码结构' : 'guide/struct.md'
    - '界面开发' : 'guide/ui.md'
    - '算法开发' : 'guide/algorithm.md'
    - '优化思路' : 'guide/optimization.md'

theme:
  name: 'material'
